[package]
name = "abar-bin"
version = "0.1.0"
authors = ["Laura Powles <laura@laurapowles.com>"]
edition = "2021"

[dependencies]
abar = "*"
chrono = "0.4"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
flume = "0.10.9"
getopts = "0.2.21"
